FROM n8nio/n8n:1.19.4

WORKDIR /home/node/

ENV NODE_ENV=production
ENV N8N_PROTOCOL=https
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=8080
ENV WEBHOOK_URL=https://n8n-io-n8n-hosting.onrender.com

EXPOSE 8080

CMD ["n8n", "start"]
